name: 'Merge to master'

on:
  schedule:
    - cron:  '10 15 * * 1-5'

jobs:
  merge-to-master:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'master'
        development_branch: 'develop'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
